import type { ReportDef, ReportGroupId, ReportId } from "./types";

export const REPORT_GROUPS: { id: ReportGroupId; label: string; hint: string }[] = [
  { id: "sales", label: "Sales Reports", hint: "Bills, services and hourly collection" },
  { id: "payments", label: "Payment Reports", hint: "Pay modes and bill grids" },
  { id: "cashier", label: "Cashier Collection", hint: "Who collected what" },
  { id: "items", label: "Item Issue", hint: "Services and retail issued from bills" },
  { id: "movement", label: "Item Movement", hint: "Fast / slow / non-moving items" },
  { id: "txn", label: "Transaction Summary", hint: "Daily bills, pax and collection" },
  { id: "tax", label: "Tax, charge & pax", hint: "Taxes, service charge, guests" },
  { id: "credit", label: "Credit Settlement", hint: "Customer credit movements" },
];

export const REPORTS: ReportDef[] = [
  {
    id: "sales-details",
    group: "sales",
    navLabel: "Sales Detail – All",
    title: "Sales Details",
    subtitle: "Bill-wise service / item details with totals (grouped by location & date)",
    searchPlaceholder: "Search bill no, item, technician...",
    hasCharts: true,
  },
  {
    id: "sales-category-summary",
    group: "sales",
    navLabel: "Sales By Category – Summary",
    title: "Sales By Category – Summary",
    subtitle: "Category-wise sales totals (grouped by location)",
    searchPlaceholder: "Search category, item...",
    hasCharts: true,
  },
  {
    id: "sales-category-detail",
    group: "sales",
    navLabel: "Sales By Category – Detail",
    title: "Sales By Category – Detail",
    subtitle: "Bill-wise category sales details (grouped by location)",
    searchPlaceholder: "Search bill no, item, technician...",
    hasCharts: true,
  },
  {
    id: "hourly-sales",
    group: "sales",
    navLabel: "Hourly Sales",
    title: "Hourly Sales",
    subtitle: "Sales value & bills per hour of day",
    searchPlaceholder: "Search hour or location...",
    hasCharts: true,
  },
  {
    id: "sales-summary",
    group: "sales",
    navLabel: "Sales Summary – ALL",
    title: "Sales Summary",
    subtitle: "Bill-wise daily collection (grouped by date)",
    searchPlaceholder: "Search bill no, technician, cashier...",
    hasCharts: true,
  },
  {
    id: "payment-summary",
    group: "payments",
    navLabel: "Payment Summary",
    title: "Payment Mode – Payment Summary",
    subtitle: "Bill-wise payment collections (grouped by location & date)",
    searchPlaceholder: "Search bill no, payment mode, cashier...",
    hasCharts: true,
  },
  {
    id: "payment-summary-wise",
    group: "payments",
    navLabel: "Pay Mode Wise",
    title: "Payment Collection – Mode Wise",
    subtitle: "Payment summary filtered by payment mode",
    searchPlaceholder: "Search bill no, payment mode, cashier...",
    extraFilter: "payMode",
    hasCharts: true,
  },
  {
    id: "payment-bill-paymode-grid",
    group: "payments",
    navLabel: "Bill Pay Mode Wise Grid",
    title: "Payment – Bill Pay Mode Wise Grid",
    subtitle: "Bill × pay mode pivot grid (grouped by location)",
    searchPlaceholder: "Search bill no, pay mode...",
    hasCharts: true,
  },
  {
    id: "cashier-collection",
    group: "cashier",
    navLabel: "Cashier Wise Sales",
    title: "Cashier Wise Sales",
    subtitle: "Per-cashier bill collections, ordered by date",
    searchPlaceholder: "Search cashier or bill no...",
    hasCharts: true,
  },
  {
    id: "cashier-payment-breakdown",
    group: "cashier",
    navLabel: "Payment Break Down",
    title: "Payment Break Down",
    subtitle: "Cashier-wise payment mode breakdown",
    searchPlaceholder: "Search cashier or mode...",
    hasCharts: true,
  },
  {
    id: "cashier-breakdown-grid",
    group: "cashier",
    navLabel: "Payment Break Down – Grid",
    title: "Payment Break Down – Grid",
    subtitle: "Bill × pay-mode grid per cashier",
    searchPlaceholder: "Search bill no, pay mode...",
    hasCharts: true,
  },
  {
    id: "service-charge",
    group: "tax",
    navLabel: "Service Charge",
    title: "Service Charge Report",
    subtitle: "Technician-wise service charge collections",
    searchPlaceholder: "Search technician, location, date...",
    hasCharts: true,
  },
  {
    id: "tax-vat",
    group: "tax",
    navLabel: "Tax Report",
    title: "Taxes Report",
    subtitle: "Bill-wise tax breakdown",
    searchPlaceholder: "Search bill no, date...",
    hasCharts: true,
  },
  {
    id: "pax-count",
    group: "tax",
    navLabel: "Pax Count",
    title: "Pax Count",
    subtitle: "Average pax per bill & spending per pax",
    searchPlaceholder: "Search bill no, date...",
    hasCharts: true,
  },
  {
    id: "credit-history",
    group: "credit",
    navLabel: "Credit History",
    title: "Credit History",
    subtitle: "Customer credit transactions",
    searchPlaceholder: "Search customer code or name...",
    hasCharts: true,
  },
  {
    id: "credit-pay-history",
    group: "credit",
    navLabel: "Payment History",
    title: "Credit Payment History",
    subtitle: "Customer payments vs invoices with balances",
    searchPlaceholder: "Search customer, bill, invoice...",
    hasCharts: true,
  },
  {
    id: "credit-account-detail",
    group: "credit",
    navLabel: "Account Detail",
    title: "Credit Account Detail",
    subtitle: "Customer account trace — INV / PAY / CHG movements",
    searchPlaceholder: "Search customer, bill, invoice...",
    hasCharts: true,
  },
  {
    id: "menu-item-issue",
    group: "items",
    navLabel: "Item Issue",
    title: "Item Issue",
    subtitle: "Department-wise issued services and retail items",
    searchPlaceholder: "Search item code, name, dept...",
    hasCharts: true,
  },
  {
    id: "menu-item-issue-date",
    group: "items",
    navLabel: "Menu Item Issue By Date",
    title: "Item Issue By Date",
    subtitle: "Issued items sectioned by date",
    searchPlaceholder: "Search item code, name, dept...",
    hasCharts: true,
  },
  {
    id: "item-movement",
    group: "movement",
    navLabel: "Item Movement",
    title: "Item Movement",
    subtitle: "Fast / slow / non moving items",
    searchPlaceholder: "Search item code or name...",
    hasCharts: true,
  },
  {
    id: "transaction-summary",
    group: "txn",
    navLabel: "Transaction Summary By Date",
    title: "Transaction Summary By Date",
    subtitle: "Daily bills, pax and collection by location",
    searchPlaceholder: "Search date, location...",
    hasCharts: true,
  },
];

export function reportById(id: string): ReportDef | undefined {
  return REPORTS.find((r) => r.id === id);
}

export function isReportId(id: string): id is ReportId {
  return REPORTS.some((r) => r.id === id);
}

export function reportsInGroup(group: ReportGroupId): ReportDef[] {
  return REPORTS.filter((r) => r.group === group);
}
